# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AcrCli < Formula
  desc "Small release-ready Go CLI"
  homepage "https://github.com/alexcamposruiz/acr-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexcamposruiz/acr-cli/releases/download/v0.1.0/acr-cli_darwin_amd64.tar.gz"
      sha256 "0178eff4a095230ecc17f9f18a7771946cb49f277046cf64d27261875664df25"

      define_method(:install) do
        bin.install "acrcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexcamposruiz/acr-cli/releases/download/v0.1.0/acr-cli_darwin_arm64.tar.gz"
      sha256 "9bc9f089a9b8f82882f8fa556f1b016b2ce3505aaf58681c301b61bf3db01dd7"

      define_method(:install) do
        bin.install "acrcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexcamposruiz/acr-cli/releases/download/v0.1.0/acr-cli_linux_amd64.tar.gz"
      sha256 "3a821c43ca06f79d823a55d554a6f2d7739cf79908c8eaa98ecc3cb4335a60c7"
      define_method(:install) do
        bin.install "acrcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexcamposruiz/acr-cli/releases/download/v0.1.0/acr-cli_linux_arm64.tar.gz"
      sha256 "36d841efb40aca5fd2464e8317b4b9bae83bc901637abb4c3bf748c73688037f"
      define_method(:install) do
        bin.install "acrcli"
      end
    end
  end

  test do
    system "#{bin}/acrcli", "doctor"
  end
end
